// beer-store-client-webpack-react/src/views/beer-listing.jsx
import React from "react";

import {beerservice} from "../api";

import {TopBar} from "../components/top-bar";
import {SearchBar} from "../components/search-bar";
import {BeerItem} from "../components/beer-item";

import List from '@material-ui/core/List';
import IconButton from "@material-ui/core/IconButton";
import VisibilityIcon from "@material-ui/icons/Visibility";

export class BeerListing extends React.Component {
  // @babel/plugin-proposal-class-properties
  state = {params: {search: "", page: 1, pageSize: 10}, list: []};

  componentDidMount() {
    this.busca();
  }

  busca = params => {
    if (params) {
      this.state.params = params;
      this.setState(this.state);
    }
    beerservice.list(this.state.params).then(ret => {
      this.state.list = ret.data;
      this.setState(this.state);
    });
  };

  render() {
    const {params, list} = this.state;
    return (
      <div>
        <TopBar left={"Beer Listing"} />
        <SearchBar params={params} list={list} busca={this.busca} />
        <List>
          {list.map(beer => (
            <BeerItem beer={beer} key={beer.idbeer}>
              <IconButton href={`#/beer-details/${beer.idbeer}`}>
                <VisibilityIcon/>
              </IconButton>
            </BeerItem>
          ))}
        </List>
      </div>
    );
  }
}

// beer-store-client-browserify-vuejs/src/views/beer-listing.vue
<template>
  <div>
    <topbar>
      <h1 slot="left">Beer Listing</h1>
    </topbar>
    <md-layout md-gutter md-column>
      <searchbar @onsearch="dosearch" :resultlist="beerlist"></searchbar>
      <beer-item v-for="beer in beerlist" :key="beer.idbeer" :beer="beer">
        <md-button
          slot="heading-options"
          class="md-icon-button"
          @click="$router.push(`/beer-details/${beer.idbeer}`)"
        >
          <md-icon>visibility</md-icon>
        </md-button>
      </beer-item>
    </md-layout>
  </div>
</template>

<script>
const { beerservice } = require("../api");
module.exports = {
  name: "BeerListing",
  data: _ => ({
    page: 1,
    beerlist: []
  }),
  created() {
    this.dosearch();
  },
  methods: {
    async dosearch(s) {
      const ret = await beerservice.list(s);
      this.beerlist = ret.data;
    }
  }
};
</script>
