// beer-store-client-browserify-vuejs/src/components/beer/beer-item.vue
<template>
  <md-card>
    <md-card-header v-if="beer">
      <md-avatar>
        <img :src="mediaservice.url(beer.idmedia)" />
      </md-avatar>
      <md-card-header-text>
        <div class="md-title">{{beer.titlebeer}}</div>
        <div class="md-caption">{{beer.descriptionbeer}}</div>
      </md-card-header-text>
      <slot name="heading-options"></slot>
    </md-card-header>
  </md-card>
</template>

<script>
const { mediaservice } = require("../../api")
module.exports = {
  name: "BeerItem",
  props: ["beer"],
  data: _ => ({ mediaservice })
}
</script>

<style>
</style>

// beer-store-client-webpack-reactjs/src/components/beer-item.jsx
import React from "react";

import {mediaservice} from "../api";

import {withStyles} from "@material-ui/core/styles";

import Avatar from "@material-ui/core/Avatar";
import ListItem from "@material-ui/core/ListItem";
import ListItemIcon from "@material-ui/core/ListItemIcon";
import ListItemText from "@material-ui/core/ListItemText";
import ListItemSecondaryAction from "@material-ui/core/ListItemSecondaryAction";

const BeerItem_ = ({beer, children}) => {
  return (
    <ListItem>
      <ListItemIcon>
        <Avatar alt="beer icon" src={mediaservice.url(beer.idmedia)} />
      </ListItemIcon>
      <ListItemText primary={beer.titlebeer} secondary={beer.descriptionbeer}/>
      <ListItemSecondaryAction>{children}</ListItemSecondaryAction>
    </ListItem>
  );
};

export const BeerItem = withStyles({})(BeerItem_);
